### ISSUE TITLE
OTA Spark 4 flash fails over ethernet

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-firmware#326]
> I'll provide some more insight, then. We created a VLAN for the controller and Spark 4 to share with a /29 network. We have Ubuntu 20.04.3 server installed in a VM with that network as the only interface. Spark 4 is on a passive PoE injector as the only wiring to it with the LAN side plugged into an access port tagged to the same VLAN. I can see the Web GUI and the Web GUI can communicate with the Spark. The firmware that shipped would not update over the Web GUI. Process would start, Spark would beep as if it were booting up, but no progress after that. I just flashed the firmware URL you sent and they are now communicating.

**Comment by Jonmccombs** [comment]
I have almost the same issue. I bought the Spark 4 hooked it up to ethernet and it communicated with brewblox just fine through update process since brewblox says update is available. I snap shot of error feedback from brewblox is below.
Service running
Service automatically connects to controller
Service connected to controller
Handshake performed
Firmware not compatible
Valid device ID
Service not synchronized

I  reset unit three times and I never get farther then this step. You can not access Spark 4 data like the Spark One. The screen on the Spark 4 shows ethernet address and if I setup wifi the wifi address. But updates either media do the same thing. Any suggestions?

**Comment by steersbob** [comment]
The problem appears for OTA (in-UI) flashing when the Spark is connected over ethernet. A workaround is to either OTA flash over Wifi, or connect the Spark over USB, and run `brewblox-ctl flash`.

**Comment by Jonmccombs** [comment]
It was fixed when I hooked it to USB. All set after flash everything worked great!
